# SPDX-FileCopyrightText: 2025 diggsweden/rest-api-profil-lint-processor
#
# SPDX-License-Identifier: EUPL-1.2

openapi: '3.0.0'
info:
  version: 1.0.0
  title: DOK
  description: >
    När dokumentationen består av flera stycken kan också större än-tecknet användas.
    Då ersätts radbrytningar med mellanslag.
    Tomma rader bevaras däremot som styckeavgränsare.

    When the documentation consists of multiple paragraphs, the greater-than operator can be used.
    This converts line breaks into spaces.
    However, empty lines are preserved as paragraph separators.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: 'Find out more about the API info text goes here'
  url: https://valid-url-example.com
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
              example:
              - id: 3
                name: Pamela
              - id: 4
                name: Christa
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema: # Request body contents
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
              example:
              - id: 5
                name: Karen
              - id: 6
                name: Tess
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
              example: ''
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
  /items:
    get:
      summary: Get items
      responses:
        '200':
          description: Successful response
          content:
            application/yaml:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
              example:
              - id: 11
                name: Ted
              - id: 12
                name: Fred

  /items2:
    post:
      summary: Create item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
              example:
              - id: 15
                name: Herbert
              - id: 16
                name: Nils

      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
  /items3:
    get:
      summary: Get items
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
              example:
              - id: 17
                name: Pete
              - id: 18
                name: Tom
  /items4:
    post:
      summary: Create item
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string                    
              example:
              - id: 19
                name: thing1
              - id: 20
                name: thing2
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Pet'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      example: 'Woooo12'
